"""Markdown and JSON report generation for local defensive testing."""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from app.config import LAB_DISCLAIMER, REPORT_DIR
from app.models import Finding


def _now() -> str:
  """Return a stable UTC timestamp for reports."""
  return datetime.now(UTC).replace(microsecond=0).isoformat()


def _slugify(value: str) -> str:
  """Create a filesystem-safe slug."""
  slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.strip().lower()).strip("-")
  return slug or "report"


def _finding_to_dict(finding: Finding | dict[str, Any]) -> dict[str, Any]:
  """Normalize a finding object or dictionary for rendering."""
  if isinstance(finding, Finding):
    return finding.to_dict()
  return dict(finding)


def generate_markdown_report(
  *,
  title: str,
  report_type: str,
  scope: str,
  findings: list[Finding | dict[str, Any]],
  summary: str = "",
  generated_at: str | None = None,
  extra: dict[str, Any] | None = None,
) -> str:
  """Render a complete Markdown report."""
  timestamp = generated_at or _now()
  normalized = [_finding_to_dict(item) for item in findings]
  lines = [
    f"# {title}",
    "",
    f"- Report type: {report_type}",
    f"- Date and time: {timestamp}",
    f"- Scope: {scope}",
    f"- Disclaimer: {LAB_DISCLAIMER}",
    "",
    "## Summary",
    "",
    summary or "Local defensive validation report generated by the lab.",
    "",
    "## Findings",
    "",
  ]

  if not normalized:
    lines.extend(["No findings were recorded.", ""])
  for index, finding in enumerate(normalized, start=1):
    lines.extend(
      [
        f"### {index}. {finding.get('name', 'Finding')}",
        "",
        f"- Severity: {finding.get('severity', finding.get('status', 'INFO'))}",
        f"- Status: {finding.get('status', 'INFO')}",
        f"- Target: {finding.get('target', scope)}",
        f"- Evidence: {finding.get('evidence', 'No evidence recorded.')}",
        f"- Recommendation: {finding.get('recommendation', 'Review and harden as needed.')}",
        "",
        str(finding.get("summary", "No summary recorded.")),
        "",
      ]
    )

  lines.extend(["## Next steps", "", "Review WARN and CRIT findings, apply hardening, and rerun checks.", ""])

  if extra:
    lines.extend(["## Additional context", "", "```json", json.dumps(extra, indent=2), "```", ""])

  return "\n".join(lines)


def write_report(
  *,
  report_type: str,
  scope: str,
  findings: list[Finding | dict[str, Any]],
  title: str | None = None,
  summary: str = "",
  extra: dict[str, Any] | None = None,
  output_dir: Path | None = None,
) -> dict[str, Path]:
  """Write matching Markdown and JSON report files."""
  destination = output_dir or REPORT_DIR
  destination.mkdir(parents=True, exist_ok=True)
  timestamp = _now()
  report_title = title or report_type.replace("-", " ").title()
  stem = f"{datetime.now(UTC).strftime('%Y%m%d-%H%M%S')}-{_slugify(report_type)}"
  normalized = [_finding_to_dict(item) for item in findings]

  payload = {
    "title": report_title,
    "report_type": report_type,
    "generated_at": timestamp,
    "scope": scope,
    "summary": summary,
    "findings": normalized,
    "next_steps": "Review WARN and CRIT findings, apply hardening, and rerun checks.",
    "disclaimer": LAB_DISCLAIMER,
    "extra": extra or {},
  }

  markdown = generate_markdown_report(
    title=report_title,
    report_type=report_type,
    scope=scope,
    findings=normalized,
    summary=summary,
    generated_at=timestamp,
    extra=extra,
  )
  markdown_path = destination / f"{stem}.md"
  json_path = destination / f"{stem}.json"
  markdown_path.write_text(markdown, encoding="utf-8")
  json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
  return {"markdown": markdown_path, "json": json_path}


def build_advisory_markdown(fields: dict[str, str]) -> str:
  """Create a responsible disclosure advisory draft from form fields."""
  ordered_fields = [
    ("Title", "title"),
    ("Product", "product"),
    ("Vendor or maintainer", "vendor_or_maintainer"),
    ("Affected version", "affected_version"),
    ("Fixed version", "fixed_version"),
    ("Vulnerability type", "vulnerability_type"),
    ("CWE candidate", "cwe_candidate"),
    ("CVSS candidate", "cvss_candidate"),
    ("Attack preconditions", "attack_preconditions"),
    ("Impact", "impact"),
    ("Reproduction summary", "reproduction_summary"),
    ("Evidence", "evidence"),
    ("Mitigation", "mitigation"),
    ("Disclosure timeline", "disclosure_timeline"),
    ("Credits", "credits"),
  ]
  title = fields.get("title") or "Responsible Disclosure Draft"
  lines = [
    f"# {title}",
    "",
    f"Generated: {_now()}",
    "",
    f"Disclaimer: {LAB_DISCLAIMER}",
    "",
  ]
  for label, key in ordered_fields:
    value = fields.get(key, "").strip() or "TBD"
    lines.extend([f"## {label}", "", value, ""])
  lines.extend(
    [
      "## Local defensive testing note",
      "",
      "This draft should describe validation performed only in an authorized local lab or approved scope.",
      "",
    ]
  )
  return "\n".join(lines)
